### ISSUE TITLE
UIのタブ表示から消えた

### ISSUE THREAD

**Issue by taka-0770** [SignalFlagZ/sd-civitai-browser#52]
*** Error executing callback ui_tabs_callback for C:\stable-diffusion-webui\extensions\sd-webui-civbrowser\scripts\civsfz_ui.py
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\stable-diffusion-webui\extensions\sd-webui-civbrowser\scripts\civsfz_ui.py", line 755, in on_ui_tabs
        Components(downloader, tab)  # (tab)
      File "C:\stable-diffusion-webui\extensions\sd-webui-civbrowser\scripts\civsfz_ui.py", line 39, in __init__
        self.civitai = CivitaiModels()
      File "C:\stable-diffusion-webui\extensions\sd-webui-civbrowser\scripts\civsfz_api.py", line 335, in __init__
        super().__init__()
      File "C:\stable-diffusion-webui\extensions\sd-webui-civbrowser\scripts\civsfz_api.py", line 153, in __init__
        self.getOptions()
      File "C:\stable-diffusion-webui\extensions\sd-webui-civbrowser\scripts\civsfz_api.py", line 224, in getOptions
        data = self.requestApiOptions(url, query)
      File "C:\stable-diffusion-webui\extensions\sd-webui-civbrowser\scripts\civsfz_api.py", line 211, in requestApiOptions
        data = json.loads(response.text)
      File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

civitaiがサイトダウンして復活後このエラーが出てstable diffusionのタグ表示から消えて使用できなくなりました

**Comment by taka-0770** [comment]
再インストールしたら治りました

**Comment by SignalFlagZ** [comment]
Thank you for reporting the problem.
The cause is unknown, but it is probably not a problem with this extension.
This issue is closed. If anyone has the same issue, please reopen it.
