### ISSUE TITLE
【Forge】Forge branch displays error on startup and CivBrowser tab is not displayed

### ISSUE THREAD

**Issue by SignalFlagZ** [SignalFlagZ/sd-civitai-browser#56]
**Describe the bug**
Forge branch displays error on startup.
`ModuleNotFoundError: No module named 'scripts.civsfz_filemanage'`
And the CivBrowser tab doesn't appear.

**To Reproduce**
1. Start Forge
2. Many errors are displayed in the console
3. When I open the browser, there is no CivBrowser tab

**Expected behavior**
No errors are displayed and the CivBrowser tab appears.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome, FireFox
 - UI and Version: Forge f2.0.1v1.10.1-previous-298-g243952f3
 - CivBrowser Version: Forge branch. 2.2.0

**Additional context**
```
      File "D:\StableDiffusion\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-civbrowser\scripts\civsfz_api.py", line 12, in <module>
        from scripts.civsfz_filemanage import generate_model_save_path2, extensionFolder
    ModuleNotFoundError: No module named 'scripts.civsfz_filemanage'
...
      File "D:\StableDiffusion\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-civbrowser\scripts\civsfz_downloader.py", line 15, in <module>
        from scripts.civsfz_filemanage import makedirs, removeFile, extensionFolder, open_folder
    ModuleNotFoundError: No module named 'scripts.civsfz_filemanage'
...
      File "D:\StableDiffusion\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-civbrowser\scripts\civsfz_ui.py", line 19, in <module>
        from scripts.civsfz_api import CivitaiModels
    ModuleNotFoundError: No module named 'scripts.civsfz_api'
...
      File "D:\StableDiffusion\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-civbrowser\scripts\settings.py", line 5, in <module>
        from scripts.civsfz_api import APIInformation
    ModuleNotFoundError: No module named 'scripts.civsfz_api'
```

**Comment by SignalFlagZ** [comment]
If the gguf package is installed, it will cause a conflict and the extension will not load.
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1134#issuecomment-2290925628
Uninstall gguf from Python virtual environment.
Enter the virtual environment and `pip uninstall gguf`
Or install a new Forge.

**Comment by taka-0770** [comment]
最新版のForgeでは　pip uninstall gguf　しなくても少し重いですが動くようです

**Comment by taka-0770** [comment]
本日のForgeのアプデでcivbrowserの表示が消えました

*** Error executing callback ui_tabs_callback for C:\stable-diffusion-webui-forge\extensions\sd-webui-civbrowser\scripts\civsfz_ui.py
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui-forge\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\stable-diffusion-webui-forge\extensions\sd-webui-civbrowser\scripts\civsfz_ui.py", line 786, in on_ui_tabs
        Components(downloader, tab)  # (tab)
      File "C:\stable-diffusion-webui-forge\extensions\sd-webui-civbrowser\scripts\civsfz_ui.py", line 48, in __init__
        self.civitai = CivitaiModels()
      File "C:\stable-diffusion-webui-forge\extensions\sd-webui-civbrowser\scripts\civsfz_api.py", line 335, in __init__
        super().__init__()
      File "C:\stable-diffusion-webui-forge\extensions\sd-webui-civbrowser\scripts\civsfz_api.py", line 153, in __init__
        self.getOptions()
      File "C:\stable-diffusion-webui-forge\extensions\sd-webui-civbrowser\scripts\civsfz_api.py", line 224, in getOptions
        data = self.requestApiOptions(url, query)
      File "C:\stable-diffusion-webui-forge\extensions\sd-webui-civbrowser\scripts\civsfz_api.py", line 211, in requestApiOptions
        data = json.loads(response.text)
      File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

---

この様な感じにエラーが出ています
