### ISSUE TITLE
sd-civitai-browserがタブに表示されません  No module named 'tkinter'

### ISSUE THREAD

**Issue by kohxtpbb250** [SignalFlagZ/sd-civitai-browser#7]
SignalFlagZさんのsd-civitai-browserがタブに表示されません。
試しにsd-civitai-browser plusをインストールしたらタブに表示されました。
何か改善方法はございますでしょうか。
よろしくお願いいたします。

version: v1.6.0  •  python: 3.10.10  •  torch: 2.0.1+cu118  •  xformers: 0.0.21  •  gradio: 3.41.2  •  checkpoint: 6ce0161689

**Comment by SignalFlagZ** [comment]
報告ありがとうございます。
civitai browserをインストールした場合はSD web UIを一旦終了して立ち上げ直します。既存の場合、SD web UIはExtensionsの更新をしません。Extensions→InstalledでCheck for updatesボタンを押して更新します。その後 念のためSD web UIを立ち上げ直します。
また、Linux Mac環境での動作確認はしていません。Firefoxも。その場合はより詳しく教えていただけるとありがたいです。

**Comment by kohxtpbb250** [comment]
> 報告ありがとうございます。 civitai browserをインストールした場合はSD web UIを一旦終了して立ち上げ直します。既存の場合、SD web UIはExtensionsの更新をしません。Extensions→InstalledでCheck for updatesボタンを押して更新します。その後 念のためSD web UIを立ち上げ直します。 また、Linux Mac環境での動作確認はしていません。Firefoxも。その場合はより詳しく教えていただけるとありがたいです。

返信ありがとうございます。web UIの立ち上げ直しまではしてます。ブラウザはChromeですがPaperspaceで動かしています。

**Comment by SignalFlagZ** [comment]
関係しそうなエラーメッセージは何か出ていませんか？
クラウドで怪しそうなのはtkinterというライブラリでしょうか。独自のライブラリをインストールしないとならない可能性が考えられます。

**Comment by SignalFlagZ** [comment]
決め打ちで Linuxなら tkinter をインストールする設定を追加してみました。 70b19a00c119c7d82edb19cdb22c742074482a13
civitai-browserを更新して試してみてください。
Mac はデフォで入っているのだろうか？

**Comment by kohxtpbb250** [comment]
> sd-civitai-browser

おはようございます。
返信ありがとうございます。
早速対処いただきありがとうございます。
元々インストールした後は仰る通りtkinterのエラーが出ていたのでChatGPTから下記をインストールしたらいいと回答を得て実行しましたが、インストールされているにもかかわらずtkinterのエラーが出てました。現状はこのような状況です。
!pip install tk
Requirement already satisfied: tk in /usr/local/lib/python3.10/dist-packages (0.1.0)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

先ほど元々あったsd-civitai-browserのフォルダを削除し昨日修正いただいたsd-civitai-browserをURLから新規インストールしましたら下記のメッセージが出まして現状タブに表示されていない状況です。

*** Error loading script: civitai_api.py
    Traceback (most recent call last):
      File "/storage/stable-diffusion/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/storage/stable-diffusion/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/civitai_api.py", line 7, in <module>
        from scripts.file_manage import extranetwork_folder
      File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/file_manage.py", line 14, in <module>
        import tkinter as tk
    ModuleNotFoundError: No module named 'tkinter'


*** Error loading script: file_manage.py
    Traceback (most recent call last):
      File "/storage/stable-diffusion/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/storage/stable-diffusion/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/file_manage.py", line 14, in <module>
        import tkinter as tk
    ModuleNotFoundError: No module named 'tkinter'

*** Error loading script: gui_civitai.py
    Traceback (most recent call last):
      File "/storage/stable-diffusion/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/storage/stable-diffusion/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/gui_civitai.py", line 4, in <module>
        from scripts.civitai_api import civitaimodels
      File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/civitai_api.py", line 7, in <module>
        from scripts.file_manage import extranetwork_folder
      File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/file_manage.py", line 14, in <module>
        import tkinter as tk
    ModuleNotFoundError: No module named 'tkinter'

コードを読み切らないのでいらない情報までペーストしているかもしれませんが何か対処法があればご検討いただければ大変嬉しいです。
よろしくお願いします。

**Comment by SignalFlagZ** [comment]
> ModuleNotFoundError: No module named 'tkinter'

tkinterが入っていませんね。tkinterのインストールはwebui起動の最初の方で行われます。コンソールのもっと上の方にインストールメッセージが表示されます。

> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. **_It is recommended to use a virtual environment instead_**:

 手動でインストールした時、tkinterを違う所へインストールしています。SD web UIの仮想環境にインストールしていないので認識されなかったのでしょう。

Paperspaceのシステムが謎なので未知のシステムの時はtkinterをインストールするよう変更しました。 ea35e1b8d583220757dad93bd2e23008423cc299
civitai-browserを更新してSD web UI立ち上げ、最初の方で "requirements for sd-civitai-browser"と表示されればインストール成功です。

**Comment by kohxtpbb250** [comment]
> > ModuleNotFoundError: No module named 'tkinter'
> 
> tkinterが入っていませんね。tkinterのインストールはwebui起動の最初の方で行われます。コンソールのもっと上の方にインストールメッセージが表示されます。
> 
> > WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. **_It is recommended to use a virtual environment instead_**:
> 
> 手動でインストールした時、tkinterを違う所へインストールしています。SD web UIの仮想環境にインストールしていないので認識されなかったのでしょう。
> 
> Paperspaceのシステムが謎なので未知のシステムの時はtkinterをインストールするよう変更しました。 [ea35e1b](https://github.com/SignalFlagZ/sd-civitai-browser/commit/ea35e1b8d583220757dad93bd2e23008423cc299) civitai-browserを更新してSD web UI立ち上げ、最初の方で "requirements for sd-civitai-browser"と表示されればインストール成功です。

丁寧な返信ありがとうございます！
今すぐに試したいのですが今日は試すことができないので試したら報告いたします！

**Comment by kohxtpbb250** [comment]
> > ModuleNotFoundError: No module named 'tkinter'
> 
> tkinterが入っていませんね。tkinterのインストールはwebui起動の最初の方で行われます。コンソールのもっと上の方にインストールメッセージが表示されます。
> 
> > WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. **_It is recommended to use a virtual environment instead_**:
> 
> 手動でインストールした時、tkinterを違う所へインストールしています。SD web UIの仮想環境にインストールしていないので認識されなかったのでしょう。
> 
> Paperspaceのシステムが謎なので未知のシステムの時はtkinterをインストールするよう変更しました。 [ea35e1b](https://github.com/SignalFlagZ/sd-civitai-browser/commit/ea35e1b8d583220757dad93bd2e23008423cc299) civitai-browserを更新してSD web UI立ち上げ、最初の方で "requirements for sd-civitai-browser"と表示されればインストール成功です。

返信と修正いただきありがとうございます。
お返事が遅くなりまして申し訳ありません。

改めて実施してみましてまずインストールしているsd-civitai-browserをアップデートしても改善しなかったのでフォルダを削除して新規インストールしましたがやはり下記のエラーが出ます。

*** Error loading script: civitai_api.py
    Traceback (most recent call last):
      File "/storage/stable-diffusion/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/storage/stable-diffusion/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/civitai_api.py", line 7, in <module>
        from scripts.file_manage import extranetwork_folder
      File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/file_manage.py", line 14, in <module>
        import tkinter as tk
    ModuleNotFoundError: No module named 'tkinter'

---
*** Error loading script: file_manage.py
    Traceback (most recent call last):
      File "/storage/stable-diffusion/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/storage/stable-diffusion/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/file_manage.py", line 14, in <module>
        import tkinter as tk
    ModuleNotFoundError: No module named 'tkinter'

---
*** Error loading script: gui_civitai.py
    Traceback (most recent call last):
      File "/storage/stable-diffusion/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/storage/stable-diffusion/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/gui_civitai.py", line 4, in <module>
        from scripts.civitai_api import civitaimodels
      File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/civitai_api.py", line 7, in <module>
        from scripts.file_manage import extranetwork_folder
      File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/file_manage.py", line 14, in <module>
        import tkinter as tk
    ModuleNotFoundError: No module named 'tkinter'

参考までにPaperspaceで動かしている元々のコードは下記になります。
https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace/blob/master/StableDiffusionUI_Voldemort_paperspace.ipynb

WebUIを立ち上げる前の早い段階であらかじめ!pip install tkでtkinterをインストールすればうまくいく可能性はありますでしょうか。
よろしくお願いいたします。

**Comment by kohxtpbb250** [comment]
> > ModuleNotFoundError: No module named 'tkinter'
> 
> tkinterが入っていませんね。tkinterのインストールはwebui起動の最初の方で行われます。コンソールのもっと上の方にインストールメッセージが表示されます。
> 
> > WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. **_It is recommended to use a virtual environment instead_**:
> 
> 手動でインストールした時、tkinterを違う所へインストールしています。SD web UIの仮想環境にインストールしていないので認識されなかったのでしょう。
> 
> Paperspaceのシステムが謎なので未知のシステムの時はtkinterをインストールするよう変更しました。 [ea35e1b](https://github.com/SignalFlagZ/sd-civitai-browser/commit/ea35e1b8d583220757dad93bd2e23008423cc299) civitai-browserを更新してSD web UI立ち上げ、最初の方で "requirements for sd-civitai-browser"と表示されればインストール成功です。

import platform
 
ur = platform.uname()
print(ur)
uname_result(system='Windows', node='DESKTOP-BIU2TIF', release='10', version='10.0.19042', machine='AMD64', processor='Intel64 Family 6 Model 158 Stepping 10, GenuineIntel')
 
print(ur.system) # Windows
print(ur.release) # 10
print(ur.processor) # Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
uname_result(system='Linux', node='naxw7bhz39', release='5.19.0-45-generic', version='#46~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 7 15:06:04 UTC 20', machine='x86_64')
Linux
5.19.0-45-generic
x86_64

よくはわかりませんがコードを動かしたらLinuxで動いてるみたいです。

**Comment by SignalFlagZ** [comment]
> WebUIを立ち上げる前の早い段階であらかじめ!pip install `tk`でtkinterをインストールすればうまくいく可能性はありますでしょうか。

`tk` は違うパッケージを指します。 tkinterの場合は `Tk` です。でも今回の件には関係しません。

真面目に調べたら `tkinter`というプロジェクトはpipに存在しませんでした。`pytk`に変更・修正しましたので試してください。

知識があるならaptでpython3-tkをインストールするのが早いのですが、何の事かわからないなら気にしなくて良いです。

**Comment by kohxtpbb250** [comment]
お世話になります。
先ほど入れてみましたが同じようなことエラーが出ます。
お手間を掛けまして申し訳ありません。

Error loading script: gui_civitai.py
    Traceback (most recent call last):
      File "/storage/stable-diffusion/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/storage/stable-diffusion/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/gui_civitai.py", line 4, in <module>
        from scripts.civitai_api import civitaimodels
      File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/civitai_api.py", line 7, in <module>
        from scripts.file_manage import extranetwork_folder
      File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/file_manage.py", line 14, in <module>
        import tkinter as tk
    ModuleNotFoundError: No module named 'tkinter'

**Comment by SignalFlagZ** [comment]
貴重な報告をありがとうございます。

pipではtkinterをインストールできず、`python3-tk`をaptでインストールするしかないようです。root権限が必要でありこのプログラムからは何もできません。
`python3-tk`のインストール方法はPaperspaceのコミュニティなどで聞いてください。特殊環境なのでこれ以上の助言はできません。参考になりそうなインストール手順はこちら [stackoverflow](https://stackoverflow.com/questions/25905540/importerror-no-module-named-tkinter)
tkinterはpythonの標準モジュールなので公式には個別のインストール方法が書いてありません。https://docs.python.org/ja/3.10/library/tk.html

今後も機能拡張にtkinterを利用していく予定です。

**Comment by kohxtpbb250** [comment]
> 貴重な報告をありがとうございます。
> 
> pipではtkinterをインストールできず、`python3-tk`をaptでインストールするしかないようです。root権限が必要でありこのプログラムからは何もできません。 `python3-tk`のインストール方法はPaperspaceのコミュニティなどで聞いてください。特殊環境なのでこれ以上の助言はできません。参考になりそうなインストール手順はこちら [stackoverflow](https://stackoverflow.com/questions/25905540/importerror-no-module-named-tkinter) tkinterはpythonの標準モジュールなので公式には個別のインストール方法が書いてありません。https://docs.python.org/ja/3.10/library/tk.html
> 
> 今後も機能拡張にtkinterを利用していく予定です。

最後まで対応いただき、また今後のご助言までいただき本当にありがとうございます!後は自分で使えるところまで持っていきます。
またYouTube楽しみにしてます!!!

**Comment by kohxtpbb250** [comment]
> 貴重な報告をありがとうございます。
> 
> pipではtkinterをインストールできず、`python3-tk`をaptでインストールするしかないようです。root権限が必要でありこのプログラムからは何もできません。 `python3-tk`のインストール方法はPaperspaceのコミュニティなどで聞いてください。特殊環境なのでこれ以上の助言はできません。参考になりそうなインストール手順はこちら [stackoverflow](https://stackoverflow.com/questions/25905540/importerror-no-module-named-tkinter) tkinterはpythonの標準モジュールなので公式には個別のインストール方法が書いてありません。https://docs.python.org/ja/3.10/library/tk.html
> 
> 今後も機能拡張にtkinterを利用していく予定です。

お世話になります。
ここにコメントしていいかはわかりませんがご報告です。
!sudo apt-get install -y python3-tkをノートブックに記載したら使えるようになってます。最初はコマンドプロンプトのようなterminalsで!sudo apt-get install -y python3-tkを実行してからwebuiを立ち上げるとうまくいったのですがいちいちterminalsで記載するのも手間だったので何とかノートブックだけで動くようにと思っていろいろやってみました。
ほんとにwebuiからモデルやLORAがダウンロードかできるのは超絶便利です！しかも保存先まで指定できるのもとても気が利いていると思います！
今回のことで少し詳しくなれた気がしております。ご助言や対処いただきありがとうございます！これからもよろしくお願いします！

**Comment by SignalFlagZ** [comment]
追加の報告ありがとうございます。
tkinter無しでも動くモードを追加しました。制限モードです。もしもこのモードの場合はコンソールに黄色い文字でtkinterが無いよと表示します。念のため表示されていないかご確認ください。無ければtkinterが動いています。具体的には 既にあるモデルファイルをダウンロードする時に Overwrite するか確認するメッセージボックスが表示されればtkinterは動いています。

**Comment by kohxtpbb250** [comment]
あっ！今日動かしたときに､制限ありで使えるよみたいなメッセージ(英語は忘れましたが…)が出たんでそれのお陰で動いてそうですね(汗)

**Comment by SignalFlagZ** [comment]
よく考えるとtkinterはクラウドサービスでは意味が無いですね。"tkinterはローカルでしか動かない" で正解のようです。
リモートに入れてもローカルでGUIを表示する方法・プログラムが存在しないので動きようがありません。
今後の方針を見直します。

**Comment by kohxtpbb250** [comment]
> よく考えるとtkinterはクラウドサービスでは意味が無いですね。"tkinterはローカルでしか動かない" で正解のようです。 リモートに入れてもローカルでGUIを表示する方法・プログラムが存在しないので動きようがありません。 今後の方針を見直します。

ご丁寧な返信ありがとうございます！
tkinterはローカルでしか動かないんですね！それであれば潔く諦めます。もちろんSignalFlagZさんが思う拡張機能で突き進んでいただければと思います☆ここまでイレギュラー環境で使ってるのにも関わらず修正、改善、返答までいただきありがとうございます!!!
SignalFlagZさんの今回のYouTubeを見て自分の拡張機能を遠い未来(笑)作ってみたいと思います！
